language: node_js
node_js:
  - 'iojs'
install:
  - cd ./Letterpress
  - npm install
  - gulp generate:all
  - cd ..

# Disable email notifications
notifications:
  email: false

env:
  global:
  - GH_REF: github.com/Wortex17/Swashbucklers.git
  - secure: "qXDfNd2bTMJ7BAyRvKGMKNtWv1pvT/+b8n2tLEJnMnvxeFRLKST9IJx0yP+U7X9eOijX4MrwqHJsAuBGBKE/ucUZOCQzSZ1/UC0x++gwMs4r8SDl98fvxob1QQfWqSLY+N35WZvdPljGMMXB3glJNIyh4gjEIyzaUF9+qkhcfZrAkerOILA9ji2Tv24lP5z52O4W+g/q/GfRjiAI8IODHdEol+AktmlGNPoFjiNy9tuYBap3TitcDEfnG5MfEi8z8wwYC/q/COAdh1Y4M+iURlF0LOiDCGSZ8CU92BdqqZF8Og2mFsEyYta01/5AdVVlBJl2NZLXQTF8WIb9MgunR5M8mt4NF2gCMGKPYXdVhsTbmGzaNEZczcwu0G2Ul6bhR/gI2hn+wr9G6483yfXtOLunbnH8T6nyxUcdmoRFOmJ9h8mEWBd6hXs30WZiMQZSkcNMS0YZ4SXEssW+Qj1gugJyJI2GV3i5nHeq30/DYpywe02wWucektTBEEaKXXd7H3Sk3O6sXUHqf6pg9FGqKF1W2fdhbxRAGw5a1oXo2VrJhO8/xNrlzKGwbgpxH9TLOy7bqEeFopDwSAlRZMjtdSZXS/idG0rC6JvFfpgFY5oST2OFviGqQF1J0vDLYPDdKqMqkhnE30CPEM8SlgSgQ9a6pvSHd24tpAVveVVm/m8="